### ISSUE TITLE
Nondescript Exception on missing appmap.yml file

### ISSUE THREAD

**Issue by ryanmarshall** [applandinc/appmap-ruby#106]
Exception trying to open missing file should explain more specifically the file that is missing and where is should be located.  

`No such file or directory @ rb_sysopen - appmap.yml`

![Screen Shot 2021-02-17 at 11 23 53 AM](https://user-images.githubusercontent.com/118652/108256664-9fd7c480-7112-11eb-9fd8-f56be0253ee2.png)

**Comment by ryanmarshall** [comment]
I think it would make sense to add a rake file to the gem to help install appmap

`bundle exec rake appmap:install`

1.  this could add a basic appmap.yml in the exact location needed. 
2. This could auto insert into all needed files `require` statement

**Comment by kgilpin** [comment]
This would be nice. It could also add the Rails source directories,
auto-populate the project name from looking at Git, and prompt for
additional gems to add to the config.

**Comment by kgilpin** [comment]
Here’s a head start:

https://appland.org/code-gallery/appmap-auto-dependencies/

From Jared

**Comment by ryanmarshall** [comment]
Oh this is great, we should pull all this logic into `gem 'appmap'` class. Not sure why this logic would be in a separate place.

**Comment by kgilpin** [comment]
Fixed in new version.
