### ISSUE TITLE
Implement `files` command

### ISSUE THREAD

**Issue by torchello** [applandinc/appmap-ruby#140]
## Description
Lists relevant project and configuration-related files. This will be consumed by the IDE to watch for changes and poll the project status

## Output
JSON, stdout:
```json
{
  "configuration": ["Gemfile"],
  "test_directories": ["spec", “test”],
  "integration_test_directories": ["spec/request", "spec/system"],
  "appmap_directory": "tmp/appmap",
}
```

**Comment by kgilpin** [comment]
We should defer this until we have tested the flow with just init and status
