### ISSUE TITLE
Ruby: init makes a backup copy of the original Gemfile

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-ruby#167]
I have been creating copies of the Gemfile manually to recover from potential bugs quickly. It would be good if the init function created a pre-appmap backup of the Gemfile instead.

Also, creating backups of files modified by setup scripts is IMO considered a good etiquette.

**Comment by dustinbyrne** [comment]
What about `git checkout Gemfile` to revert? I think it's relatively safe to say that we'll be executing within a version controlled directory, and the file history will be preserved.

**Comment by torchello** [comment]
`appmap-agent-init` does not modify files anymore (just generates the contents of the `appmap.yml`). I think we can close this one.
