### ISSUE TITLE
bundle install failed with error ( I put gem in .gemfile at the top as recommended)

### ISSUE THREAD

**Issue by misha-tsu** [applandinc/appmap-ruby#186]
current directory: /home/server/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/appmap-0.64.0/ext/appmap
/home/server/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20210825-23872-14ulfow.rb extconf.rb
creating Makefile

current directory: /home/server/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/appmap-0.64.0/ext/appmap
make "DESTDIR=" clean

current directory: /home/server/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/appmap-0.64.0/ext/appmap
make "DESTDIR="
compiling appmap.c
In file included from /home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby.h:33,
                 from appmap.c:1:
/home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:627:1: error: ‘const’ attribute on function returning ‘void’ [-Werror=attributes]
  627 | CONSTFUNC(void rb_secure_update(VALUE));
      | ^~~~~~~~~
In file included from /home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2001,
                 from /home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby.h:33,
                 from appmap.c:1:
/home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/intern.h:257:1: error: ‘const’ attribute on function returning ‘void’ [-Werror=attributes]
  257 | CONSTFUNC(void rb_error_untrusted(VALUE));
      | ^~~~~~~~~
/home/server/.rbenv/versions/2.4.0/include/ruby-2.4.0/ruby/intern.h:259:1: error: ‘const’ attribute on function returning ‘void’ [-Werror=attributes]
  259 | CONSTFUNC(void rb_check_trusted(VALUE));
      | ^~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:242: appmap.o] Ошибка 1

make failed, exit code 2

**Comment by kgilpin** [comment]
Update : AppMap now supports 2.6, 2.7, and 3.0. 2.5 and earlier are not supported by the Ruby dev team any more.
