### ISSUE TITLE
getting "AppMap auto-configuration is currently not available for non Rails projects" in rails project

### ISSUE THREAD

**Issue by tansaku** [applandinc/appmap-ruby#217]
I'm getting:

> AppMap auto-configuration is currently not available for non Rails projects

in what is definitely a rails project - how does appmap determine if something is a rails project?

I'm working with a Rails API project - would that not work?

**Comment by kgilpin** [comment]
Hi Sam, the code is looking to see if `Gem.loaded_specs.has_key?('rails')`:

https://github.com/applandinc/appmap-ruby/blob/42c67e8a883e3a46128afccc0251ee4b3a7ca5db/lib/appmap/service/validator/config_validator.rb#L72

I've used Rails-API but honestly I don't know/recall whether that includes the `rails` gem or not. 

There are a couple of ways you might work around this problem. The first would be to add the `rails` gem to your bundle and re-run the installer. 

The second is to [configure your project manually](https://appland.com/docs/reference/appmap-ruby.html#installation). You'll need to do two things:

1) Add the `appmap` gem to your bundle. Example: 

https://github.com/land-of-apps/sample_app_6th_ed/blob/appmap-e2e/Gemfile#L4

2) Create an appmap.yml file that lists the source folders. Example:

https://github.com/land-of-apps/sample_app_6th_ed/blob/appmap-e2e/appmap.yml

You can add other source folders that you may have, and you can add Gems as well. Here's a fairly complete example: https://appland.com/docs/reference/appmap-ruby.html#configuration

**Comment by kgilpin** [comment]
And yes, a `rails-api` project will work quite nicely with AppMap.

**Comment by tansaku** [comment]
thanks - all sorted now, but for reference here was my original attempt:

```
❯ npx @appland/appmap install /Users/samueljoseph/Documents/Github/<org>/<proj>
Installing AppMap agent for us-outbound-partner-integrator...
? AppMap is about to be installed. Confirm the details below.
  Project type: Bundler
  Project directory: /Users/samueljoseph/Documents/Github/<org>/<proj>
  Git remote: origin	git@github.com:<org>/<proj>.git (fetch)
  Ruby version: 2.7.5p203
  Gem home: /Users/samueljoseph/.rvm/gems/ruby-2.7.5

  Is this correct? Yes
✔ Installing the AppMap agent...
✖ Validating the AppMap agent...
! Installation failed. View error details? Yes

AppMap auto-configuration is currently not available for non Rails projects
AppMap auto-configuration is currently not available for non Rails projects
```
and even though the installation failed I still got the gem added

```
gem 'appmap', :groups => [:development, :test]
```
and the `appmap.yml` file created automatically as a side effect.

I edited the latter to include a few more relevant folders, and set up the tests to be able to be run through Rake, but a re-run of the install fails in the same way:

```
? An appmap.yml configuration file already exists. How should the conflict be resolved? Use existing
✔ Installing the AppMap agent...
✖ Validating the AppMap agent...
! Installation failed. View error details? Yes

AppMap auto-configuration is currently not available for non Rails projects
AppMap auto-configuration is currently not available for non Rails projects
```
but so I added the rails gem as suggested, and then the app install was successful

```
? An appmap.yml configuration file already exists. How should the conflict be resolved? Use existing
✔ Installing the AppMap agent...
✔ Validating the AppMap agent...
✔ Checking the syntax of AppMap agent configuration...

   ╭──────────────────────────────────────────────────────╮
   │                                                      │
   │    Success! The AppMap agent has been installed.     │
   │   For more information on recording AppMaps, visit   │
   │    https://appland.com/docs/reference/appmap-ruby    │
   │                                                      │
   ╰──────────────────────────────────────────────────────╯

```
and I ran the tests with Rake, but in vscode it was still saying that there was no AppMap present, but I finally got it all working now by running the tests with an env var like this (which I got from the docs) and now I'm good.

```
APPMAP=true bundle exec rspec
```

thanks so much for all your help
