### ISSUE TITLE
Take the `method_source` code we need and copy it in AppMap, to not depend on `method_source` or conflict with it in the wild

### ISSUE THREAD

**Issue by symwell** [applandinc/appmap-ruby#276]
We want to take the `method_source` code we need and add it to our repo e.g. `lib/appmap/method_source`.

Then we can apply the [performance fix](https://github.com/banister/method_source/pull/78) we want in our repo. That way we can be sure not to conflict with method_source in the wild, and we will get the efficient implementation that we want.

Give proper attribution and then we can be done with it.

https://applanding.slack.com/archives/CQ5JFE1DY/p1662647402949409

**Comment by symwell** [comment]
I tried to take the `method_source` code we needed and add it to our repo but it seemed [too much work](https://github.com/applandinc/appmap-ruby/compare/sw/include_method_source_in_appmap?expand=1)
- copy only some files over, rather than the `.git` dir or the spec files.  It would not include its testcases.
- add attribution
- change it to be under the AppMap module (I think we're supposed to do that.)
- run the testcases, which don't pass now, with some error

It seems easier (2 lines of code change) to point our `method_source` gem to a custom branch
https://github.com/applandinc/appmap-ruby/compare/sw/use_method_source_from_custom_branch?expand=1

**Comment by kgilpin** [comment]
But it can still conflict with the `method_source` that may be used by the
user's project...

**Comment by kgilpin** [comment]
I think it's worth completing that draft - with the code we don't used
(such as extracting method source) removed.

**Comment by symwell** [comment]
[Simpler change](https://github.com/applandinc/appmap-ruby/compare/sw/part_custom_method_source?expand=1) that extracts only the code we need from`method_source` with testcases passing.

**Comment by kgilpin** [comment]
Looks nice. We should raise our own exception class too

https://github.com/applandinc/appmap-ruby/compare/sw/part_custom_method_source?expand=1#diff-c7d68f4ec3680a58ebfd3aa08e9e7e1aa17b885e25ea3587e12f99a160b3c09cR75
