### ISSUE TITLE
Seg Fault When Running Tests on Redmine

### ISSUE THREAD

**Issue by jaredKreppein** [applandinc/appmap-ruby#74]
Segfault occurs when running Appmap tests on [Redmine](https://github.com/land-of-apps/redmine). 
`[BUG] Segmentation fault at 0x0000000000000000`

Appears to happen on multiple tests such as:  
- /home/travis/build/land-of-apps/redmine/test/functional/boards_controller_test.rb:120
- /home/travis/build/land-of-apps/redmine/test/integration/api_test/projects_test.rb:37

[Redmine logs](https://travis-ci.com/github/land-of-apps/redmine/jobs/385853078)

**Comment by kgilpin** [comment]
What's the Ruby version that is being used here? Maybe a more updated Ruby would unblock the mapping of Redmine.

**Comment by jaredKreppein** [comment]
Travis is using 2.6.5
`$ rvm use default - Using /home/travis/.rvm/gems/ruby-2.6.5`
